### ISSUE TITLE
No news or feuser information in list plugin

### ISSUE THREAD

**Issue by p-view** [cdaecke/md_unreadnews#2]
When i use the list plugin theres no news or feuser information in the entry.
Only when i put in a fluid fdebug tag for unreadnews in the template i get it all.
Is it maybe a loading, depence or cache problem?

**Comment by cdaecke** [comment]
Thanks for reporting!

I have just released a news version of the extension (v3.0.1), which addresses this issue.

**Comment by p-view** [comment]
THX perfect!
