### ISSUE TITLE
Trying to access array offset on value of type null in BaseController

### ISSUE THREAD

**Issue by machwatt** [cdaecke/md_unreadnews#3]
I got an error 
PHP Warning: Trying to access array offset on value of type null in ***typo3conf/ext/md_unreadnews/Classes/Controller/BaseController.php line 69

with TYPO3 11.5 and PHP 8.1

My suggestion to fix this would be to implement the Context API here as in https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/Context/Index.html .

You would change this code

```php
if ($GLOBALS['TSFE']->fe_user->user['uid']) {
    $this->loggedinUserUid = (int)$GLOBALS['TSFE']->fe_user->user['uid'];
}
```

to the following:

```php
$context = GeneralUtility::makeInstance(Context::class);
$this->loggedinUserUid = $context->getPropertyFromAspect('frontend.user', 'id', null);
```
There is an use statement necessary: `use TYPO3\CMS\Core\Context\Context;`

I just tested this in my actual project and the deletion of unread entry is working as before.
I did not test this in previous versions but as this documentation is for v 10.4 is assume, that it works there too.

**Comment by cdaecke** [comment]
I have just updated the code to make the extension compatible with TYPO3 v12. Is this fixing you problem? Can you test with current master?

**Comment by cdaecke** [comment]
New version of the extension is released.

If you have still problems, please open a news issue.
