### ISSUE TITLE
TYPO3 12.4 Compatible Version

### ISSUE THREAD

**Issue by devtroll** [cdaecke/md_unreadnews#4]
Is there any information yet when this extension will be available for TYPO3 v12?

Greetings

**Comment by cdaecke** [comment]
A version for TYPO3 v12 is planned, but there is no release date yet.

Pull requests are very welcome!

**Comment by cdaecke** [comment]
@devtroll I have just updated the code. Are you able to test the current master?

**Comment by cdaecke** [comment]
Final version for TYPO3 v12 is released.
